/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapp.view;

import chatapp.controllers.LoginController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Dell
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_dang_nhap = new javax.swing.JLabel();
        lb_tai_khoan = new javax.swing.JLabel();
        txt_tai_khoan = new javax.swing.JTextField();
        lb_mat_khau = new javax.swing.JLabel();
        txt_mat_khau = new javax.swing.JTextField();
        btn_dang_nhap = new javax.swing.JButton();
        lb_dang_ky = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_dang_nhap.setText("ĐĂNG NHẬP");
        lb_dang_nhap.setName(""); // NOI18N

        lb_tai_khoan.setText("TÀI KHOẢN");
        lb_tai_khoan.setName(""); // NOI18N

        txt_tai_khoan.setText("Nhập tài khoản");
        txt_tai_khoan.setName(""); // NOI18N

        lb_mat_khau.setText("MẬT KHẨU");
        lb_mat_khau.setName(""); // NOI18N

        txt_mat_khau.setText("Nhập mật khẩu");
        txt_mat_khau.setName(""); // NOI18N

        btn_dang_nhap.setText("ĐĂNG NHẬP");
        btn_dang_nhap.setName(""); // NOI18N
        btn_dang_nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dang_nhapActionPerformed(evt);
            }
        });

        lb_dang_ky.setText("Đăng ký tài khoản");
        lb_dang_ky.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tai_khoan)
                    .addComponent(lb_mat_khau))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dang_nhap)
                    .addComponent(btn_dang_nhap)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_tai_khoan)
                        .addComponent(txt_mat_khau, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addComponent(lb_dang_ky))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lb_dang_nhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tai_khoan)
                    .addComponent(txt_tai_khoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_mat_khau)
                    .addComponent(txt_mat_khau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_dang_nhap)
                .addGap(18, 18, 18)
                .addComponent(lb_dang_ky)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dang_nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dang_nhapActionPerformed
        // TODO add your handling code here:'
        String taiKhoan = txt_tai_khoan.getText();
        String matKhau = txt_mat_khau.getText();
        if (taiKhoan.equals("") || matKhau.equals("")) {
            //return
        }
        try {
            LoginController.login();
        } catch (IOException ex) {
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dang_nhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dang_nhap;
    private javax.swing.JLabel lb_dang_ky;
    private javax.swing.JLabel lb_dang_nhap;
    private javax.swing.JLabel lb_mat_khau;
    private javax.swing.JLabel lb_tai_khoan;
    private javax.swing.JTextField txt_mat_khau;
    private javax.swing.JTextField txt_tai_khoan;
    // End of variables declaration//GEN-END:variables
}
